// react/typescript/vite/src/App.tsx
import React, { useState } from "react";
import { InteractiveNvlWrapper } from "@neo4j-nvl/react";
import { Node, Relationship } from "@neo4j-nvl/base";

export const App = () => {
  const [nodes, setNodes] = useState<Node[]>([
    { id: "0", caption: "graphs" },
    { id: "1", caption: "everywhere" },
  ]);
  const [relationships, setRelationships] = useState<Relationship[]>([
    { from: "0", to: "1", id: "10", caption: "are" },
  ]);

  return (
    <div style={{ width: "100%", height: "75vh" }}>
      <InteractiveNvlWrapper
        nvlOptions={{ initialZoom: 3 }}
        nodes={nodes}
        rels={relationships}
        mouseEventCallbacks={{
          onZoomAndPan: true,
          onPan: true,
        }}
      />
    </div>
  );
};

// angular/vite/src/app/app.ts
import { Component, signal, AfterViewInit } from '@angular/core';
import type { Node, NvlOptions, Relationship } from "@neo4j-nvl/base";
import { NVL } from "@neo4j-nvl/base";
import {
  ZoomInteraction,
  PanInteraction,
} from "@neo4j-nvl/interaction-handlers";

@Component({
  selector: 'app-root',
  templateUrl: './app.html',
  standalone: true,
  imports: []
})
export class App implements AfterViewInit {
  protected readonly title = signal('vite');

  ngAfterViewInit(): void {
    const container = document.getElementById("nvl-container");
    const nodes: Node[] = [
      { id: "0", caption: "graphs" },
      { id: "1", caption: "everywhere" },
    ];
    const relationships: Relationship[] = [
      { from: "0", to: "1", id: "0-1", caption: "are" },
    ];
    const options: NvlOptions = { initialZoom: 2.6, disableWebWorkers: true };

    if (container) {
      const nvl = new NVL(container, nodes, relationships, options);
      const zoom = new ZoomInteraction(nvl);
      const pan = new PanInteraction(nvl);
    } else {
      console.error("Container element not found");
    }
  }
}
